[package]
name = "pangalactic_store"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_cbor = "0.11.1"
serde = "1.0"

[dependencies.pangalactic_b64]
path = "../pangalactic_b64"
