[package]
name = "dagwasm-guests"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
include_dir.workspace = true

[dev-dependencies]
tokio.workspace = true

[dev-dependencies.dagwasm-store]
path = "../store"
version = "^0.1.0"

[dev-dependencies.dagwasm-dagio]
path = "../dagio"
version = "^0.1.0"

[dev-dependencies.dagwasm-schemata]
path = "../schemata"
version = "^0.1.0"

[dev-dependencies.dagwasm-dir]
path = "../dir"
version = "^0.1.0"

[dev-dependencies.dagwasm-host]
path = "../host"
version = "^0.1.0"

[dev-dependencies.dagwasm-memstore]
path = "../memstore"
version = "^0.1.0"

[build-dependencies]
anyhow.workspace = true
