[package]
name = "pangalactic-guests"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
include_dir.workspace = true

[dev-dependencies]
async-trait.workspace = true
simple_logger.workspace = true
tokio.workspace = true

[dev-dependencies.pangalactic-store]
path = "../store"
version = "^0.1.0"

[dev-dependencies.pangalactic-dagio]
path = "../dagio"
version = "^0.1.0"

[dev-dependencies.pangalactic-schemata]
path = "../schemata"
version = "^0.1.0"

[dev-dependencies.pangalactic-dir]
path = "../dir"
version = "^0.1.0"
features = [
  "host",
]

[dev-dependencies.pangalactic-host]
path = "../host"
version = "^0.1.0"

[dev-dependencies.pangalactic-memstore]
path = "../stores/mem"
version = "^0.1.0"

[dev-dependencies.pangalactic-log]
path = "../log"
version = "^0.1.0"

[dev-dependencies.pangalactic-linkkind]
path = "../linkkind"
version = "^0.1.0"

[build-dependencies]
anyhow.workspace = true
