[package]
name = "dagwasm-guests"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
include_dir.workspace = true

[dev-dependencies]
tokio.workspace = true

[dev-dependencies.dagwasm-dagio]
path = "../dagio"
version = "^0.1.0"

[dev-dependencies.dagwasm-dir]
path = "../dir"
version = "^0.1.0"

[dev-dependencies.dagwasm-host]
path = "../host"
version = "^0.1.0"

[dev-dependencies.dagwasm-memstore]
path = "../memstore"
version = "^0.1.0"

[build-dependencies]
anyhow.workspace = true
