[package]
name = "pangalactic-guests"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
include_dir.workspace = true

[dev-dependencies]
async-trait.workspace = true
simple_logger.workspace = true
tokio.workspace = true

[dev-dependencies.pangalactic-dagio]
workspace = true

[dev-dependencies.pangalactic-schemata]
workspace = true

[dev-dependencies.pangalactic-dir]
workspace = true
features = [
  "host",
]

[dev-dependencies.pangalactic-host]
workspace = true

[dev-dependencies.pangalactic-store]
workspace = true

[dev-dependencies.pangalactic-store-mem]
workspace = true

[dev-dependencies.pangalactic-log]
workspace = true

[dev-dependencies.pangalactic-linkkind]
workspace = true

[build-dependencies]
anyhow.workspace = true
