[package]
name = "pangalactic-cli-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
pangalactic-endpoint.workspace = true
pangalactic-globset.workspace = true
pangalactic-manifest.workspace = true
pangalactic-runopt.workspace = true
pangalactic-seed.workspace = true
pangalactic-std-store.workspace = true
tokio.workspace = true

[dev-dependencies]
anyhow-std.workspace = true
test-case.workspace = true
pangalactic-cli-seed.workspace = true
pangalactic-test-dir.workspace = true
pangalactic-test-runner.workspace = true
