[package]
name = "pangalactic_logger"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3"
log = "0.4.14"

[dependencies.simple_logger]
version = "1.13.0"
features = ["stderr"]

[dependencies.pangalactic_errorutil]
path = "../pangalactic_errorutil"
