[package]
name = "pangalactic-globset"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
globset.workspace = true
serde.workspace = true
