[package]
name = "pangalactic-path"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
pangalactic-link.workspace = true
pangalactic-linkkind.workspace = true
pangalactic-dir.workspace = true
serde.workspace = true

[dev-dependencies]
pangalactic-link = { workspace = true, features = ["testutil"] }
pangalactic-unittest-utils.workspace = true
test-case.workspace = true
