[package]
name = "pangalactic_signpair"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_sodium = "0.10.2"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.pangalactic_sodiuminit]
path = "../pangalactic_sodiuminit"

[dev-dependencies]
test-case = "1.2.0"

[dev-dependencies.pangalactic_logger]
path = "../pangalactic_logger"
