[package]
name = "pangalactic-subsdb"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
rusqlite.workspace = true
tracing.workspace = true
