[package]
name = "pangalactic-storepath"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
pangalactic-link.workspace = true
pangalactic-linkkind.workspace = true
pangalactic-dir.workspace = true
serde.workspace = true

[dev-dependencies]
test-case.workspace = true
pangalactic-link = { workspace = true, features = ["testutil"] }
