[package]
name = "pangalactic"
description = "A placeholder; Perhaps someday a revision control + build tool?"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
