[workspace]
members = [
  "dagio",
  "dir",
  "guest",
  "guests",
  "handle",
  "host",
  "linkkind",
  "log",
  "memstore",
  "primitives",
  "schemata",
  "serialization",
  "store",
  "table",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
anyhow = "1.0.66"
async-trait = "0.1.58"
blake3 = "1.3.1"
derive_more = "0.99.17"
include_dir = "0.7.3"
log = "0.4.17"
once_cell = "1.17.0"
simple_logger = "4.0.0"
test-case = "2.2.2"

[workspace.dependencies.tokio]
version = "1.21.2"
features = [
  "io-util",
  "rt",
  "macros",
]

[workspace.dependencies.wasmtime]
version = "2.0.2"
features = [
  "async",
]
