[workspace]
members = [
  "pangalactic_app",
  "pangalactic_appdirs",
  "pangalactic_codec",
  "pangalactic_codecpath",
  "pangalactic_cryptopubsub",
  "pangalactic_cryptostore",
  "pangalactic_dirstore",
  "pangalactic_errorutil",
  "pangalactic_fs",
  "pangalactic_hashspool",
  "pangalactic_logger",
  "pangalactic_memstore",
  "pangalactic_node",
  "pangalactic_nodestore",
  "pangalactic_secretbox",
  "pangalactic_signpair",
  "pangalactic_sodiuminit",
  "pangalactic_storage",
  "pangalactic_store",
  "pg",
  "pg-store",
]
