[workspace]
members = [
  "pangalactic_b64",
  "pangalactic_cryptostore",
  "pangalactic_dirnode",
  "pangalactic_dirstore",
  "pangalactic_hashspool",
  "pangalactic_memstore",
  "pangalactic_store",
]
