[workspace]
resolver = "2"
members = [
  "cli",
  "dagio",
  "dir",
  "guest",
  "guest-procmacro",
  "guests",
  "handle",
  "host",
  "layer-cidmeta",
  "link",
  "linkkind",
  "log",
  "primitives",
  "schemata",
  "serialization",
  "store/mem",
  "store/trait",
  "table",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]

# Local crates with paths clarified:
pangalactic-cli =             { path = "cli"             }
pangalactic-dagio =           { path = "dagio"           }
pangalactic-dir =             { path = "dir"             }
pangalactic-guest =           { path = "guest"           }
pangalactic-guest-procmacro = { path = "guest-procmacro" }
pangalactic-guests =          { path = "guests"          }
pangalactic-handle =          { path = "handle"          }
pangalactic-hash =            { path = "hash"            }
pangalactic-host =            { path = "host"            }
pangalactic-layer-cidmeta =   { path = "layer-cidmeta"   }
pangalactic-linkkind =        { path = "linkkind"        }
pangalactic-link =            { path = "link"            }
pangalactic-log =             { path = "log"             }
pangalactic-primitives =      { path = "primitives"      }
pangalactic-schemata =        { path = "schemata"        }
pangalactic-serialization =   { path = "serialization"   }
pangalactic-store-mem =       { path = "store/mem"       }
pangalactic-store =           { path = "store/trait"     }
pangalactic-table =           { path = "table"           }

# Dependencies external to this workspace:
anyhow = "1.0.66"
async-trait = "0.1.58"
blake3 = "1.3.1"
clap = { version = "4.4.11", features = ["derive", "unstable-doc" ] }
derive_more = "0.99.17"
include_dir = "0.7.3"
log = "0.4.17"
once_cell = "1.17.0"
proc-macro2 = "1.0.49"
quote = "1.0.23"
simple_logger = "4.0.0"
test-case = "2.2.2"

[workspace.dependencies.syn]
version = "1.0.107"
features = [
  "full",
  "extra-traits",
]

[workspace.dependencies.tokio]
version = "1.24.1"
# TODO: Push features into specific crates that consume them:
features = [
  "io-util",
  "rt",
  "macros",
]

[workspace.dependencies.wasmtime]
version = "2.0.2"
features = [
  "async",
]
