[workspace]
members = [
  "pangalactic_appdirs",
  "pangalactic_cli",
  "pangalactic_codec",
  "pangalactic_cryptostore",
  "pangalactic_dirstore",
  "pangalactic_errorutil",
  "pangalactic_fs",
  "pangalactic_hashspool",
  "pangalactic_logger",
  "pangalactic_memstore",
  "pangalactic_node",
  "pangalactic_nodestore",
  "pangalactic_publisher",
  "pangalactic_store",
]
