[workspace]
members = [
  "pangalactic_b64",
  "pangalactic_cryptostore",
  "pangalactic_dagnode",
  "pangalactic_dagwasm",
  "pangalactic_dirstore",
  "pangalactic_hashspool",
  "pangalactic_store",
]
