[workspace]
members = [
  "pangalactic_appdirs",
  "pangalactic_cli",
  "pangalactic_codec",
  "pangalactic_cryptostore",
  "pangalactic_dirstore",
  "pangalactic_hashspool",
  "pangalactic_memstore",
  "pangalactic_node",
  "pangalactic_store",
]
