[package]
name = "pangalactic"
description = "Pangalactic deterministic computation on the universal directed acyclic graph."
version = "0.1.0"
authors = ["Pangloss <pangloss@utopia>"]

[dependencies]
wasmi = "*"
