[package]
name = "pangalactic_secretbox"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sodiumoxide = "0.2.7"
derive_more = "0.99.14"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.pangalactic_codec]
path = "../pangalactic_codec"

[dependencies.pangalactic_sodiuminit]
path = "../pangalactic_sodiuminit"

[dev-dependencies]
test-case = "1.2.0"

[dev-dependencies.pangalactic_logger]
path = "../pangalactic_logger"
