[package]
name = "pangalactic-schemata"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
dagio = [
  "async-trait",
  "pangalactic-dagio",
  "pangalactic-hostdir",
  "pangalactic-store",
]

[dependencies]
anyhow.workspace = true
async-trait = { workspace = true, optional = true }
pangalactic-dagio = { workspace = true, optional = true }
pangalactic-dir.workspace = true
pangalactic-hostdir = { workspace = true, optional = true }
pangalactic-store = { workspace = true, optional = true }
