[package]
name = "dagwasm-schemata"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dagio = [
  "anyhow",
  "async-trait",
  "dagwasm-store",
  "dagwasm-dagio",
  "dagwasm-dir",
]

[dependencies.anyhow]
workspace = true
optional = true

[dependencies.async-trait]
workspace = true
optional = true

[dependencies.dagwasm-store]
path = "../store"
version = "^0.1.0"
optional = true

[dependencies.dagwasm-dagio]
path = "../dagio"
version = "^0.1.0"
optional = true

[dependencies.dagwasm-dir]
path = "../dir"
version = "^0.1.0"
optional = true
