[package]
name = "dagwasm-schemata"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true

[dependencies.dagwasm-store]
path = "../store"
version = "^0.1.0"

[dependencies.dagwasm-dagio]
path = "../dagio"
version = "^0.1.0"

[dependencies.dagwasm-dir]
path = "../dir"
version = "^0.1.0"
