[package]
name = "pangalactic-schemata"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
dagio = [
  "async-trait",
  "pangalactic-store",
  "pangalactic-dagio",
]

[dependencies]
anyhow.workspace = true

[dependencies.pangalactic-dir]
workspace = true

[dependencies.async-trait]
workspace = true
optional = true

[dependencies.pangalactic-store]
workspace = true
optional = true

[dependencies.pangalactic-dagio]
workspace = true
optional = true
