[package]
name = "pangalactic-schemata"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
store = [
  "pangalactic-store",
  "pangalactic-layer-storedir",
]

[dependencies]
anyhow.workspace = true
pangalactic-dir.workspace = true
pangalactic-layer-cidmeta.workspace = true
pangalactic-link.workspace = true
pangalactic-store = { workspace = true, optional = true }
pangalactic-layer-storedir = { workspace = true, optional = true }
