[package]
name = "pangalactic-runopt"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
pangalactic-log.workspace = true
tracing.workspace = true
