[package]
name = "pg"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.14"
log = "0.4.14"
simple_logger = "1.11.0"

[dependencies.pangalactic]
path = "../pangalactic"

[dependencies.tokio]
version = "1.6.1"
features = ["macros", "rt-multi-thread"]
