[package]
name = "pangalactic-pubsub"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek.workspace = true
rand.workspace = true
rand_core = "0.9.3"
