[package]
name = "pangalactic-pubsub"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ed25519-dalek = { workspace = true, features = [ "serde" ] }
rand.workspace = true
serde.workspace = true
