[package]
name = "test_output_is_hello_world"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
pangalactic-guest.workspace = true
