[package]
name = "dagwasm-host"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
log.workspace = true
tokio.workspace = true
wasmtime.workspace = true

[dependencies.dagwasm-store]
path = "../store"
version = "^0.1.0"

[dependencies.dagwasm-dagio]
path = "../dagio"
version = "^0.1.0"

[dependencies.dagwasm-schemata]
path = "../schemata"
version = "^0.1.0"
features = [
  "dagio",
]

[dependencies.dagwasm-dir]
path = "../dir"
version = "^0.1.0"

[dependencies.dagwasm-handle]
path = "../handle"
version = "^0.1.0"

[dependencies.dagwasm-linkkind]
path = "../linkkind"
version = "^0.1.0"

[dependencies.dagwasm-table]
path = "../table"
version = "^0.1.0"

[dependencies.dagwasm-primitives]
path = "../primitives"
version = "^0.1.0"
