[package]
name = "pangalactic-host"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
log.workspace = true
tokio.workspace = true
wasmtime.workspace = true

[dependencies.pangalactic-store]
path = "../store/trait"
version = "^0.1.0"

[dependencies.pangalactic-dagio]
path = "../dagio"
version = "^0.1.0"

[dependencies.pangalactic-schemata]
path = "../schemata"
version = "^0.1.0"
features = [
  "dagio",
]

[dependencies.pangalactic-dir]
path = "../dir"
version = "^0.1.0"
features = [
  "host",
]

[dependencies.pangalactic-handle]
path = "../handle"
version = "^0.1.0"

[dependencies.pangalactic-linkkind]
path = "../linkkind"
version = "^0.1.0"

[dependencies.pangalactic-table]
path = "../table"
version = "^0.1.0"

[dependencies.pangalactic-primitives]
path = "../primitives"
version = "^0.1.0"
