[package]
name = "dagwasm-host"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
wasmtime.workspace = true

[dependencies.dagwasm-blobstore]
path = "../blobstore"

[dependencies.dagwasm-dagify]
path = "../dagify"

[dependencies.dagwasm-dagio]
path = "../dagio"

[dependencies.dagwasm-derivation]
path = "../derivation"

[dependencies.dagwasm-handle]
path = "../handle"

[dependencies.dagwasm-table]
path = "../table"
