[package]
name = "pangalactic-host"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
log.workspace = true
tokio.workspace = true
wasmtime.workspace = true

[dependencies.pangalactic-store]
workspace = true

[dependencies.pangalactic-dagio]
workspace = true

[dependencies.pangalactic-schemata]
workspace = true
features = [
  "dagio",
]

[dependencies.pangalactic-dir]
workspace = true
features = [
  "host",
]

[dependencies.pangalactic-handle]
workspace = true

[dependencies.pangalactic-linkkind]
workspace = true

[dependencies.pangalactic-table]
workspace = true

[dependencies.pangalactic-primitives]
workspace = true
