[package]
name = "pangalactic-layer-cidmeta"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
derive_more.workspace = true
tokio.workspace = true

[dependencies.pangalactic-serialization]
path = "../serialization"
version = "^0.1.0"

[dependencies.pangalactic-store]
path = "../store"
version = "^0.1.0"

[dependencies.pangalactic-hash]
path = "../hash"
version = "^0.1.0"
