[package]
name = "pangalactic-store-mem"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
pangalactic-hash.workspace = true
pangalactic-store.workspace = true
serde.workspace = true
tokio.workspace = true
