[package]
name = "pangalactic-store-mem"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
pangalactic-hash.workspace = true
pangalactic-store.workspace = true
tokio.workspace = true
