[package]
name = "pangalactic-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
anyhow-std.workspace = true
dirs.workspace = true
once_cell.workspace = true
serde.workspace = true
tokio = { workspace = true, features = ["fs"] }
toml.workspace = true
tracing.workspace = true
