[package]
name = "pangalactic_cryptopubsub"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.14"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.pangalactic_codec]
path = "../pangalactic_codec"

[dependencies.pangalactic_secretbox]
path = "../pangalactic_secretbox"

[dependencies.pangalactic_signpair]
path = "../pangalactic_signpair"

[dev-dependencies]
test-case = "1.2.0"
