[package]
name = "pangalactic_cryptopubsub"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pangalactic_secretbox]
path = "../pangalactic_secretbox"

[dependencies.pangalactic_signpair]
path = "../pangalactic_signpair"
