[package]
name = "pangalactic-stdstore"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
pangalactic-hash.workspace = true
pangalactic-host.workspace = true
pangalactic-iowrappers.workspace = true
pangalactic-layer-cidmeta.workspace = true
pangalactic-layer-path.workspace = true
pangalactic-layer-storedir.workspace = true
pangalactic-store-dirdb.workspace = true
pangalactic-store.workspace = true
pangalactic-transfer.workspace = true
tokio = { workspace = true, features = ["fs"] }
