[package]
name = "pangalactic-dag-traversal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
futures.workspace = true
pangalactic-init-stream.workspace = true
pin-project.workspace = true
tokio-stream = { workspace = true, features = ["fs"] }
tokio.workspace = true

[dev-dependencies]
anyhow.workspace = true
test-case.workspace = true
