[package]
name = "pangalactic-dag-traversal"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tokio-stream = { workspace = true, features = ["fs"] }

[dev-dependencies]
test-case.workspace = true
tokio.workspace = true
