[package]
name = "pangalactic-revision"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
pangalactic-dir.workspace = true
pangalactic-layer-dir.workspace = true
pangalactic-link.workspace = true
pangalactic-name.workspace = true
pangalactic-store.workspace = true
