[package]
name = "pangalactic-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
pangalactic-b64.workspace = true
pangalactic-dagio.workspace = true
pangalactic-store-dirdb.workspace = true
serde.workspace = true
tokio = { workspace = true, features = [ "io-std" ] }
