[package]
name = "pangalactic-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
pangalactic-b64.workspace = true
pangalactic-dagio.workspace = true
pangalactic-layer-cidmeta.workspace = true
pangalactic-link.workspace = true
pangalactic-store-dirdb.workspace = true
pangalactic-storepath.workspace = true
pangalactic-store.workspace = true
serde.workspace = true
tokio = { workspace = true, features = [ "io-std" ] }
tracing.workspace = true
tracing-subscriber.workspace = true

[dev-dependencies]
anyhow-std.workspace = true
test-case.workspace = true
