[package]
name = "pangalactic-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
tokio = { workspace = true, features = [ "io-std" ] }
pangalactic-store.workspace = true
pangalactic-store-mem.workspace = true
