[package]
name = "gzip"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
pangalactic-guest.workspace = true
libflate.workspace = true
