[package]
name = "pangalactic-serialization"
version.workspace = true
edition.workspace = true
license.workspace = true

[features]
testutil = []

[dependencies]
anyhow.workspace = true
postcard.workspace = true
serde.workspace = true
