[package]
name = "pangalactic-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
pangalactic-cli-derive.workspace = true
pangalactic-cli-revcon.workspace = true
pangalactic-cli-seed.workspace = true
pangalactic-cli-store.workspace = true
pangalactic-runopt.workspace = true
tokio.workspace = true
