[package]
name = "pangalactic_memstore"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.pangalactic_store]
path = "../pangalactic_store"

[dependencies.pangalactic_hashspool]
path = "../pangalactic_hashspool"
