[package]
name = "pangalactic-seed"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow-std.workspace = true
anyhow.workspace = true
include_dir.workspace = true
pangalactic-config.workspace = true
pangalactic-layer-dir.workspace = true
pangalactic-link.workspace = true
pangalactic-name.workspace = true
pangalactic-store-mem.workspace = true
pangalactic-store.workspace = true
serde.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
pangalactic-host.workspace = true
pangalactic-layer-cidmeta.workspace = true
pangalactic-linkkind.workspace = true
pangalactic-log.workspace = true
pangalactic-path.workspace = true
pangalactic-schemata.workspace = true
tokio.workspace = true

[build-dependencies]
anyhow.workspace = true
