[package]
name = "pangalactic-layer-host"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
pangalactic-host.workspace = true
pangalactic-iowrappers.workspace = true
pangalactic-layer-cidmeta.workspace = true
pangalactic-layer-dir.workspace = true
pangalactic-layer-path.workspace = true
pangalactic-link.workspace = true
pangalactic-store.workspace = true
