[package]
name = "pangalactic-link"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
pangalactic-linkkind.workspace = true
serde.workspace = true
tokio.workspace = true

[dev-dependencies]
test-case.workspace = true
