[package]
name = "pangalactic-link"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true

[dependencies.pangalactic-linkkind]
workspace = true

[dependencies.pangalactic-serialization]
workspace = true

[dev-dependencies]
test-case.workspace = true
