[package]
name = "pangalactic_nodestore"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.14"
log = "0.4.14"

[dependencies.pangalactic_codec]
path = "../pangalactic_codec"

[dependencies.pangalactic_errorutil]
path = "../pangalactic_errorutil"

[dependencies.pangalactic_fs]
path = "../pangalactic_fs"

[dependencies.pangalactic_node]
path = "../pangalactic_node"

[dependencies.pangalactic_store]
path = "../pangalactic_store"
