[package]
name = "pangalactic-revcon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
anyhow-std.workspace = true
derive_more.workspace = true
