[workspace]
members = [
  "get_plan",
  "identity",
  "test_bindings_plan_is_dir",
  "test_bindings_input_is_hello_world",
  "test_input_is_hello_world",
  "test_output_is_hello_world",
  "test_plan_is_dir",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "MIT"

[workspace.dependencies]
