[package]
name = "pangalactic-config"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
dirs.workspace = true
once_cell.workspace = true
tracing.workspace = true
