[package]
name = "pangalactic-cli-seed"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
pangalactic-manifest.workspace = true
pangalactic-runopt.workspace = true
pangalactic-seed.workspace = true
pangalactic-std-store.workspace = true
tokio.workspace = true
