[package]
name = "pangalactic-cli-seed"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
pangalactic-layer-cidmeta.workspace = true
pangalactic-layer-dir.workspace = true
pangalactic-manifest.workspace = true
pangalactic-runopt.workspace = true
pangalactic-seed.workspace = true
pangalactic-store-dirdb.workspace = true
pangalactic-store-mem.workspace = true
pangalactic-store.workspace = true
tokio.workspace = true
