[package]
name = "pangalactic-cli-revcon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
pangalactic-revcon.workspace = true
pangalactic-runopt.workspace = true
pangalactic-std-store.workspace = true
tokio.workspace = true
