[package]
name = "pangalactic-dir"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
pangalactic-name.workspace = true
serde = { workspace = true, optional = true }
