[package]
name = "pangalactic-dagfs"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
derive_more.workspace = true
pangalactic-dagio.workspace = true
pangalactic-store.workspace = true
pangalactic-storepath.workspace = true
