[package]
name = "pangalactic-manifest"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
derive_more.workspace = true
pangalactic-dir.workspace = true
pangalactic-layer-dir.workspace = true
pangalactic-link.workspace = true
pangalactic-linkkind.workspace = true
pangalactic-name.workspace = true
pangalactic-nested-dir.workspace = true
pangalactic-store.workspace = true
