[package]
name = "dagwasm-guest"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.dagwasm-linkkind]
path = "../linkkind"
version = "^0.1.0"

[dependencies.dagwasm-primitives]
path = "../primitives"
version = "^0.1.0"

[dependencies.dagwasm-guest-procmacro]
path = "../guest-procmacro"
version = "^0.1.0"
