[package]
name = "create_tar"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
pangalactic-guest.workspace = true
tar.workspace = true
