[package]
name = "pangalactic-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
anyhow-std.workspace = true
async-trait.workspace = true
pangalactic-chomper.workspace = true
pangalactic-cid.workspace = true
pangalactic-serialization.workspace = true
pin-project.workspace = true
serde.workspace = true
# tokio = { workspace = true, features=["fs"] }
tokio.workspace = true # FIXME: Feature fs breaks wasm guests
