[package]
name = "pangalactic-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
pangalactic-chomper.workspace = true
pangalactic-serialization.workspace = true
anyhow.workspace = true
async-trait.workspace = true
serde.workspace = true
tokio.workspace = true
