[package]
name = "pangalactic_dagwasm"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasmi = "0.8.0"

[dependencies.pangalactic_dagnode]
path = "../pangalactic_dagnode"

[dependencies.pangalactic_store]
path = "../pangalactic_store"
