[package]
name = "pangalactic-dagio"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true

[dependencies.pangalactic-dir]
workspace = true
features = [
  "host",
]

[dependencies.pangalactic-layer-cidmeta]
workspace = true

[dependencies.pangalactic-link]
workspace = true

[dependencies.pangalactic-linkkind]
workspace = true

[dependencies.pangalactic-serialization]
workspace = true

[dependencies.pangalactic-store]
workspace = true

[dev-dependencies.pangalactic-store-mem]
workspace = true
