[package]
name = "dagwasm-dagio"
version.workspace = true
edition.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
tokio.workspace = true

[dependencies.dagwasm-dir]
path = "../dir"
version = "^0.1.0"
features = [
  "host",
]

[dependencies.dagwasm-layer-cidmeta]
path = "../layer-cidmeta"
version = "^0.1.0"

[dependencies.dagwasm-link]
path = "../link"
version = "^0.1.0"

[dependencies.dagwasm-linkkind]
path = "../linkkind"
version = "^0.1.0"

[dependencies.dagwasm-serialization]
path = "../serialization"
version = "^0.1.0"

[dependencies.dagwasm-store]
path = "../store"
version = "^0.1.0"

[dev-dependencies.dagwasm-memstore]
path = "../memstore"
version = "^0.1.0"
