[package]
name = "pangalactic_hashspool"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake3 = "0.3.8"
derive_more = "0.99.14"

[dependencies.serde]
version = "1.0"
features = ["derive"]
