[package]
name = "pangalactic-revcon"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow-std.workspace = true
anyhow.workspace = true
derive_more.workspace = true
pangalactic-config.workspace = true
pangalactic-dag-transfer.workspace = true
pangalactic-globset.workspace = true
pangalactic-layer-dir.workspace = true
pangalactic-link.workspace = true
pangalactic-linkpath.workspace = true
pangalactic-name.workspace = true
pangalactic-store.workspace = true
serde.workspace = true
tokio.workspace = true
