[package]
name = "pangalactic-asynctryiter"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
pangalactic-name.workspace = true
tokio.workspace = true
