[package]
name = "pangalactic_sodiuminit"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sodiumoxide = "0.2.7"
lazy_static = "1.2.0"
log = "0.4.14"
