[package]
name = "pangalactic-std-store"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
pangalactic-dag-transfer.workspace = true
pangalactic-endpoint.workspace = true
pangalactic-hash.workspace = true
pangalactic-host.workspace = true
pangalactic-layer-cidmeta.workspace = true
pangalactic-layer-dir.workspace = true
pangalactic-link.workspace = true
pangalactic-store-dirdb.workspace = true
pangalactic-store-mem.workspace = true
pangalactic-store.workspace = true
