[package]
name = "pangalactic-name"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aliri_braid.workspace = true
serde.workspace = true
thiserror.workspace = true
