# This is a basic workflow to help you get started with Actions

name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: cargo +nightly fmt -- --check

      - run: cargo +nightly test --verbose

      - run: cargo +nightly build

      - run: cargo +nightly doc
