on: [pull_request]

name: cargo-checkmate Continuous Integration

jobs:
  cargo-checkmate:
    name: cargo-checkmate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - run: rustup target add x86_64-unknown-linux-gnu wasm32-unknown-unknown
      - run: rustup component add clippy --target x86_64-unknown-linux-gnu
      - run: rustup component add rustfmt --target x86_64-unknown-linux-gnu
      - run: cargo install cargo-audit
      - run: cargo audit
      - run: cargo install cargo-checkmate
      - run: RUST_BACKTRACE=full cargo-checkmate
