name: nix caching
on:
  push:
    branches: [main, ci-caching]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/determinate-nix-action@v3

      - name: Generate nix caching key
        id: compute-nix-cache-hash
        run: |
          nix eval --raw .#bin-cargo-artifacts \
            | sed 's/^/nix_cache_hash=/' \
            | tee -a "$GITHUB_OUTPUT"

      - name: Cache nix prerequisite derivations
        id: cache-nix-bin-cargo-artifacts
        uses: actions/cache@v4
        env:
          cache-name: cache-nix-bin-cargo-artifacts
        with:
          path: /tmp/gh-nix-cache/
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ steps.compute-nix-cache-hash.outputs.nix_cache_hash }}
      - name: Checking for Cache Refresh
        run: ./util/nix-cache-restore-or-build.sh bin-cargo-artifacts /tmp/gh-nix-cache
